import "./globals.css";
import { Inconsolata } from "next/font/google";
import Navbar from "./component/Navbar";

// Importing Google Font with a Latin subset
const inconsolata = Inconsolata({ subsets: ["latin"] });

// Metadata for the page (used in Next.js app directory)
export const metadata = {
	title: "Create cool stuff using hooshmandlab",
	description: "Generated by create next app",
};

// RootLayout component that wraps around your page components
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			{/* Applying the imported font to the entire body */}
			<body className={inconsolata.className}>
				{/* Rendering the Navbar component */}
				<Navbar />
				{/* Main content area with a max width for the layout */}
				<main className="mx-auto max-w-6xl px-8 py-20">{children}</main>
			</body>
		</html>
	);
}
