import "./globals.css";
import { Inconsolata } from "next/font/google";
import Navbar from "./component/Navbar";
import Providers from "./providers";

// Importing Google Font with a Latin subset
const inconsolata = Inconsolata({ subsets: ["latin"] });

// Metadata for the page (used in Next.js app directory)
export const metadata = {
	title: "Create cool stuff using hooshmandlab",
	description: "Generated by create next app",
};

// RootLayout component that wraps around your page components
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={inconsolata.className}>
				<Navbar />
				<main className="mx-auto max-w-6xl px-8 py-20">
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	);
}
